#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,9,43&i=15,16,17&v=27,26,25 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define L10N_LANGUAGE			RU


#endif
