#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,9,45&i=&v= */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */
/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define L10N_LANGUAGE			RU
#define I2S_INTERNAL			true

/* Дополнительные опции */
#define VOLUME_STEP           5
#define BUFLEN              190
#define BITRATE_FULL          1
#define VOLUME_LOGARITHMIC true 


#endif
