[env:lolin_s2_mini]
platform = espressif32
; Указываем правильную плату для S2 Mini
board = lolin_s2_mini
framework = arduino

; Убираем жесткую привязку к COM-порту, чтобы PIO искал его сам
; upload_port = COM15 
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_ignore = AsyncTCP
lib_deps = 
   adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306       ; <--- ДОБАВИТЬ ЭТО
    adafruit/Adafruit BusIO  
    mathertel/OneButton 
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.8 
    marvinroger/AsyncMqttClient

; Настройки памяти для чипа ESP32-S2FNR2
board_build.mcu = esp32s2
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
; Для встроенной флеш S2 обычно используется cdc/dio
board_build.partitions = min_spiffs.csv

build_flags = 
    -I . 
    -I src 
    -I src/AsyncWebServer
    -D CORE_DEBUG_LEVEL=3 
    -D ENABLE_MQTT=1
    ; КРИТИЧЕСКИЕ ФЛАГИ ДЛЯ S2 MINI:
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    ; Исправление для корректной работы кэша PSRAM на S2
    -mfix-esp32-psram-cache-issue 
