[env:wemos_d1_r32]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_ignore = 
    AsyncTCP


lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    XPT2046_Touchscreen
    mathertel/OneButton
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.8
    ;https://github.com/marvinroger/async-mqtt-client.git
    ;https://github.com/me-no-dev/AsyncTCP.git
    marvinroger/AsyncMqttClient

platform_packages =
    framework-arduinoespressif32

board_build.flash_mode = qio
board_build.bootloader = dio
board_build.partitions = min_spiffs.csv

build_flags =
    -I .
    -I src
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -I src/AsyncWebServer    ; <--- ДОБАВЬТЕ ЭТУ СТРОКУ
    -DENABLE_MQTT=1

    